Make compatible with svg.js 3 branch
svgdotjs/svg.draw.js pull request #48
Opened 2019-04-13 14:32 UTC by JanMisker

Using SVG.List instead of SVG.Set

2019-04-13 20:15 UTC, Fuzzyma commented
Thanks for your contribution!
Its nice, that only such a little change is needed. However, its not only code changes which are required for the new version. Here is a list which we try to verify for every 3.0 ready plugin:

- esm importable
- no dependency to global SVG (so SVG is imported via esm)
- no dist-files in the repo. Instead, they are uploaded to the release page and npm
- a d.ts file to have typings
- enforded standard style via linter with "our" rules

I know thats  a bit overwhelming but have a look how it was done in e.g. [svg.draggable.js](https://github.com/svgdotjs/svg.draggable.js). Especially the npm scripts are interesting in this regard.

2019-04-13 22:05 UTC, JanMisker commented
Sure makes sense, good to have the list. I'll have a look.
I only saw svg.select.js and that is still 'old style' it seems, even though compatible with 3.0?

2019-04-13 23:45 UTC, JanMisker commented
How about this? I took _inspiration_ for the package.json, rollup config and eslint config from svg.draggable.js.

Also I got rid of the draw.extend because I didn't really see how to implement it properly with esm, and I replaced it with a `registerPlugin` function exported from svg.draw.js.

2019-04-15 07:16 UTC, Fuzzyma requested changes
Nice work. It looks all correct except 2 minor changes required

2019-04-15 07:16 UTC, Fuzzyma commented on src/svg.draw.js
> +    this.parent = el.parent(Nested) || el.parent(Doc)
`Nested` doesnt exist anymore. It's all `Doc` now. Just use `el.parent()` without any parameter

2019-04-15 07:16 UTC, Fuzzyma commented on src/svg.draw.js
> +    var shapesArr = shapes.trim().split(/\s+/)
For splitting you can use the regex `delimiter` which is exported with the `regex` object (`import {regex} from ...`)

2019-04-15 07:17 UTC, Fuzzyma commented
Albeit this PR makes draw usable with svg.js v3.x it is not really using the new features. Thats why I planned to rework the whole plugin. However, getting it served like that I think I will publish it and rework when I find some time in the future

2019-04-15 07:30 UTC, JanMisker commented
I just found out about the awesome svg.js tools a couple of days ago, so still figuring out how stuff exactly works. I suppose the release notes are best way to find out about differences and new features in v3.x ?

Are you asking me to make the changes or will you process them?

2019-04-15 07:38 UTC, Fuzzyma commented
Yes the changelog is a good point to start. You can also take a look at the advent calender with code examples we posted on twitter. Or you just head directly to the codepen collection: https://codepen.io/collection/XpwMLO/#

Yes, I would like to ask you to fix those 2 things I pointed out. That would be awesome!

2019-04-17 18:40 UTC, JanMisker commented
Did you see I made the changes?
And just wondering: how are you thinking to re-implement the extension? I'm thinking there could be more integrating between the draw, select and resize extensions??

2019-04-17 18:46 UTC, Fuzzyma commented
Sorry, no didn't see it. I wanted to make it cleaner in general. I rewrote some parts of this plugin as part of other work and found that there are more elegant solutions as the current one.

Which integrations of the plug-ins do you have in mind? I tried to decouple them as good as I could when I wrote them.

2019-04-17 19:19 UTC, JanMisker commented
I really like the plugin structure that allows me to draw anything I can `SVG.invent`, for example things with paths. See [here for an example](https://gist.github.com/JanMisker/6e084e398490318080c1ed8359a5498d) (not 100% sure that gist works, I copied some code from a test).
However it is not possible to use `selectize` on those inventions.

2019-04-18 10:36 UTC, Fuzzyma commented
> I really like the plugin structure that allows me to draw anything I can SVG.invent

I wouldnt have thought that anyone would use that feature :D. In svg.js v3.x invent is unfortunately gone. But you can just use class inheritence instead ^^.
Why does select not work? You just have to implement a size function for your invented shape, or am I wrong here?

2019-04-18 15:59 UTC, Fuzzyma commented
One more thing I just found :D.
You put the dist folder into git ignore. Thats correct, but when you do that, you need to explicitely delete this folder from git before. Otherwise they just stay in the repo and thats not what we want :)

2019-12-09 10:32 UTC, hujiulong commented on src/svg.draw.js
> +      this.parent.on('click.draw', this.start)
Need to be changed into:
```js
this.parent.on('click.draw', e => {
  this.start(e);
})
```
Because `this.start `will be overwritten later

2020-02-19 23:32 UTC, Fuzzyma commented
Sooo why exactly this was never merged? :D

2020-06-14 20:56 UTC, Bernix01 commented
any update on this?

2020-06-15 03:07 UTC, Fuzzyma commented
Unfortunately not. No time at hand

2020-08-01 02:48 UTC, mindok commented
svg.js is great, but it seems this PR is well and truly stuck despite the best efforts of @JanMisker to keep things moving. This, unfortunately, cripples a bunch of useful functionality in svg.js v3+. Is there any alternative way to get svg.draw.js to work with svg.js v3 or do we need to use svg.js 2.x for now? Maybe it's worth releasing an alternative unofficially supported svg.draw.js if the maintainers don't have time to support the merge or do major refactors. I don't mean this in any negative way, btw - I'm incredibly grateful that these projects exist, but I do know life gets in the way sometimes. @JanMisker - are you using a private build of svg.draw.js?

2020-08-02 01:07 UTC, Bernix01 commented
@mindok I'm currently using [this fork](https://github.com/grupopulpo/svg.draw.js) based on @JanMisker great job. It's working, at least does with svg.js 3+ based on [this other fork](https://github.com/grupopulpo/svg.js). The release cycle of svg.js was very slow so I used to work with master branch but it became more prone to break builds so I forked the current master version. Now it is 3 commits behind so I believe it shouldn't have any problem.

2020-08-03 15:48 UTC, JanMisker commented
hey @mindok and @Bernix01, thanks for the kinds words ;)
I use standard svg.js but modified plugins. I must admit that after I got things working for my project I also didn't spend much time to look back at this. 
I did make another plugin to also edit drawn shapes, but I didn't document it so never published it.
I now made it publicly visible so you can at least look at it, I think it depends on my fork of svg.draw.js.
https://github.com/JanMisker/svg.edit.js

2024-06-18 10:52 UTC, Fuzzyma commented
closed in favor of #65

2024-06-18 10:53 UTC, closed without merging